name: caddy-dcoker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 5"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: lisonfan/caddy:latest
